import WomenImg from '@/assets/img/blogPost/two-women-in-front-of-board.png';

export const POSTS = [
  {
    id: 1,
    author: 'John Doe',
    date: 'Aug 23, 2023',
    title: 'Design tips for designers that cover everything you need',
    type: 'Startup',
    text: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    image: WomenImg,
  },
  {
    id: 2,
    author: 'John Doe',
    date: 'Aug 23, 2023',
    title: 'How to build rapport with your web design clients',
    type: 'Business',
    text: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    image: WomenImg,
  },
  {
    id: 3,
    author: 'John Doe',
    date: 'Aug 23, 2023',
    title: 'Logo design trends to avoid in 2022',
    type: 'Startup',
    text: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    image: WomenImg,
  },
  {
    id: 4,
    author: 'John Doe',
    date: 'Aug 23, 2023',
    title: '8 Figma design systems you can download for free today',
    type: 'Technology',
    text: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    image: WomenImg,
  },
  {
    id: 5,
    author: 'John Doe',
    date: 'Aug 23, 2023',
    title: 'Font sizes in UI design: The complete guide to follow',
    type: 'Economy',
    text: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    image: WomenImg,
  },
  {
    id: 6,
    author: 'Doe John',
    date: 'Aug 23, 2023',
    title: 'Font sizes in UI design: The complete guide to follow',
    type: 'Economy',
    text: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    image: WomenImg,
  },
  {
    id: 7,
    author: 'Doe John',
    date: 'Aug 23, 2023',
    title: '8 Figma design systems you can download for free today',
    type: 'Economy',
    text: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    image: WomenImg,
  },
  {
    id: 8,
    author: 'Doe John',
    date: 'Aug 23, 2023',
    title: 'Font sizes in UI design: The complete guide to follow',
    type: 'Economy',
    text: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    image: WomenImg,
  },
  {
    id: 9,
    author: 'Doe John',
    date: 'Aug 23, 2023',
    title: '8 Figma design systems you can download for free today',
    type: 'Economy',
    text: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    image: WomenImg,
  },
  {
    id: 10,
    author: 'Doe John',
    date: 'Aug 23, 2023',
    title: 'The complete guide to follow',
    type: 'Economy',
    text: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    image: WomenImg,
  },
];
