import React from 'react';
import type { Metadata } from 'next';
import { Inter, Sen } from 'next/font/google';
import '@/styles/reset.scss';

const sen = Sen({ subsets: ['latin'], weight: ['400', '500', '700'] });
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${inter.className} ${sen.className}`}>{children}</body>
    </html>
  );
}
