import React, { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Inter, Sen } from 'next/font/google';
import { PageParams } from '@/types/pageParams';
import '@/styles/reset.scss';
import '@/styles/global.scss';

const sen = Sen({ subsets: ['latin'], weight: ['400', '500', '700'] });
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export function generateStaticParams() {
  return [{ lang: 'en-US' }, { lang: 'de' }];
}

export default function RootLayout({
  children,
  params,
}: {
  children: ReactNode;
  params: PageParams;
}) {
  return (
    <html lang={params.locale}>
      <body className={`${inter.className} ${sen.className}`}>{children}</body>
    </html>
  );
}
